version: 2.1

jobs:
  preparation:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run:
          name: Install deps
          command: npm install
      - save_cache:
          key: v1-shopping-lists-vue-deps-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  statics-tests:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - restore_cache:
          key: v1-shopping-lists-vue-deps-cache-{{ checksum "package.json" }}
      - run:
          name: Check statics tests
          command: npm run static
  deploy:
    docker:
      - image: cimg/node:19.7.0
    environment:
      NETLIFY_AUTH_TOKEN: 67opcXXVhM9QPP4a8yF44UCXYA5rW14Ih1C0FHOZDBM
      NETLIFY_SITE_ID: 811b7ca5-9f07-4091-bcd6-323549c438a5
    steps:
      - checkout
      - restore_cache:
          key: v1-shopping-lists-vue-deps-cache-{{ checksum "package.json" }}
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Install Netlify
          command: npm install netlify-cli -g
      - run:
          name: Netlify deploy
          command: netlify deploy --prod --dir=dist --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN

workflows:
  deploy-workflow:
    jobs:
      - preparation
      - statics-tests:
          requires:
            - preparation
      - hold:
          type: approval
          requires:
            - statics-tests
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - main
